version: '3.8'

services:
  api:
    container_name: developerstore-api
    build:
      context: .
      dockerfile: src/DeveloperStore.Presentation.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=developerstore;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - developerstore-network
    restart: always

  postgres:
    container_name: developerstore-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: developerstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - developerstore-network
    restart: always

  pgadmin:
    container_name: developerstore-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - developerstore-network
    restart: always

networks:
  developerstore-network:
    driver: bridge

volumes:
  postgres-data: 